version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4-cli-node
    steps:
      - checkout
      - restore_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
      - run:
          name: composer instlal
          command: composer install
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
      - run:
          name: ralavel key generate
          command: php artisan key:generateph
      - persist_to_workspace:
          root: .
          paths: .

  test:
    docker:
      - image: circleci/php:7.4-cli-node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: unit test
          command: ./vendor/bin/phpunit

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
